run:
  name: deit_t_transmix_imnet1k_subset100
  seed: 42

model:
  name: deit_t
  num_classes: 1000
  drop_path_rate: 0.1
  pretrained: false #or true

data:
  data_dir: data/imagenet1k_subset_100pc
  img_size: 224
  crop_pct: 0.875
  interpolation: bicubic
  batch_size: 128
  num_workers: 8
  pin_memory: true
  use_randaugment: true
  ra_num_ops: 9
  ra_magnitude: 15
  random_erasing_prob: 0.25
  seed: 42

train:
  eval_every: 5
  epochs: 300 #if pretraine is true reduc to 100
  warmup_epochs: 20 #and reduce warm up to 10
  amp: true
  grad_accum_steps: 2

optim:
  name: adamw
  lr: 0.0005
  warmup_lr: 0.000001
  lr_min: 0.00001
  weight_decay: 0.05

transmix:
  prob: 1.0
  alpha: 1.0        # CutMix Beta(alpha, alpha)
  lambda_mode: mean # "attn" or "mean"
